baseURL: https://artemtech.github.io/dokumentasiku
# baseURL: http://localhost:1313
languageCode: en-US
title: Dokumentasi Artemtech
theme: cactus
disqusShortname: artemtech

menu:
  main:
  - name: home
    url: /
    weight: 1
  - name: legacy-blog
    url: https://artemtechblog.wordpress.com
    weight: 3
  - name: tentang
    url: /about
    weight: 4

params:
  description: Laman ini merupakan dokumentasi keseharian terkait hasil ngoprek dan sidik gangguan atas permasalahan yang saya alami.
  colortheme: light
  mainSection: posts
  mainSectionTitle: Postingan
  comments:
    engine: disqus  